PREFIX ?= .
include $(PREFIX)/Makefile.conf
COMPILE.cc = g++ $(CFLAGS) $(OPT) -c

headerFiles:=$(wildcard *.h *.tcc)
sourceFiles:=$(wildcard *.cpp)
files:=$(basename $(sourceFiles))
objectFiles:=$(addsuffix .o,$(files))

.PHONY: objs
objs: $(objectFiles)

.PHONY: depend
depend:
	@$(COMPILE.cc) -MM -MP *.cpp >> Makefile

# Auto generated dependencies
